import './App.css'

type Metric = {
  label: string
  description: string
  creator: number
  bau: number
  format: 'currency' | 'number' | 'percent'
  difference?: 'points'
}

const creatorCohort = {
  customers: 428,
  revenue: 82176,
  orders: 642,
}

const bauCohort = {
  customers: 6240,
  revenue: 861120,
  orders: 8174,
}

const metrics: Metric[] = [
  {
    label: 'Revenue per customer',
    description: 'Revenue generated within 12 months of first purchase',
    creator: 192,
    bau: 138,
    format: 'currency',
  },
  {
    label: 'Orders per customer',
    description: 'Average orders placed within the observation window',
    creator: 1.5,
    bau: 1.31,
    format: 'number',
  },
  {
    label: 'Repeat customer rate',
    description: 'Customers who placed at least one additional order',
    creator: 35,
    bau: 21,
    format: 'percent',
    difference: 'points',
  },
  {
    label: 'First-purchase AOV',
    description: 'Average value of the customer’s first order',
    creator: 112,
    bau: 98,
    format: 'currency',
  },
  {
    label: 'Repeat-purchase AOV',
    description: 'Average value of orders placed after the first purchase',
    creator: 160,
    bau: 128,
    format: 'currency',
  },
  {
    label: 'Repeat revenue per customer',
    description: 'Repeat-order revenue spread across the full cohort',
    creator: 80,
    bau: 40,
    format: 'currency',
  },
]

const productHalo = {
  creatorRevenuePerCustomer: 64.5,
  bauRevenuePerCustomer: 43,
  creatorCrossCategoryRate: 29,
  bauCrossCategoryRate: 17,
  creatorProductsPurchased: 2.4,
  bauProductsPurchased: 1.7,
}

const revenuePerCustomer = metrics[0]
const incrementalRevenue =
  (revenuePerCustomer.creator - revenuePerCustomer.bau) * creatorCohort.customers
const haloLift =
  productHalo.creatorRevenuePerCustomer / productHalo.bauRevenuePerCustomer

const currency = (n: number) =>
  new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: n % 1 === 0 ? 0 : 2,
  }).format(n)

const integer = (n: number) =>
  new Intl.NumberFormat('en-US', { maximumFractionDigits: 0 }).format(n)

const formatMetric = (value: number, format: Metric['format']) => {
  if (format === 'currency') return currency(value)
  if (format === 'percent') return `${value}%`
  return value.toFixed(value % 1 === 0 ? 0 : 2)
}

const CONTACT_EMAIL = 'hello@influ-sight.com'

function App() {
  return (
    <div className="page">
      <div className="shell">
        <nav className="nav" aria-label="Primary navigation">
          <a className="brand" href="/" aria-label="InfluSight home">
            Influ<span>Sight</span>
          </a>
          <div className="nav-meta">
            <span className="status-dot" aria-hidden="true" />
            Demo store
          </div>
        </nav>

        <header className="header">
          <div>
            <h1>Stop guessing your influencer ROI.</h1>
          </div>
          <div className="report-period">
            <span>Analysis window</span>
            <strong>Last 12 months</strong>
          </div>
        </header>

        <div className="sample-banner" role="status">
          <strong>Sample data for illustration.</strong>
          <span>Built with your real sales data on request.</span>
        </div>

        <section className="hero" aria-label="Incremental revenue">
          <div>
            <p className="hero-label">Incremental Revenue</p>
            <p className="hero-value">+{currency(incrementalRevenue)}</p>
            <p className="hero-detail">
              Estimated additional 12-month revenue generated by the creator
              cohort after normalizing for cohort size.
            </p>
          </div>
          <div className="hero-formula" aria-label="Incremental revenue calculation">
            <div>
              <span>Creator revenue / customer</span>
              <strong>{currency(revenuePerCustomer.creator)}</strong>
            </div>
            <span className="calculation-symbol">−</span>
            <div>
              <span>BAU revenue / customer</span>
              <strong>{currency(revenuePerCustomer.bau)}</strong>
            </div>
            <span className="calculation-symbol">×</span>
            <div>
              <span>Creator customers</span>
              <strong>{integer(creatorCohort.customers)}</strong>
            </div>
          </div>
        </section>

        <section className="section cohort-context" aria-labelledby="cohort-context-heading">
          <div className="section-heading">
            <div>
              <p className="eyebrow">Cohort context</p>
              <h2 id="cohort-context-heading">The audiences being compared</h2>
            </div>
            <span className="context-note">Totals describe scale—not performance</span>
          </div>
          <div className="cohort-cards">
            <article className="cohort-card creator-card">
              <div>
                <span className="cohort-kicker">Creator-acquired cohort</span>
                <strong>{integer(creatorCohort.customers)} customers</strong>
              </div>
              <dl>
                <div>
                  <dt>Total revenue</dt>
                  <dd>{currency(creatorCohort.revenue)}</dd>
                </div>
                <div>
                  <dt>Total orders</dt>
                  <dd>{integer(creatorCohort.orders)}</dd>
                </div>
              </dl>
            </article>
            <article className="cohort-card">
              <div>
                <span className="cohort-kicker">BAU comparison pool</span>
                <strong>{integer(bauCohort.customers)} customers</strong>
              </div>
              <dl>
                <div>
                  <dt>Total revenue</dt>
                  <dd>{currency(bauCohort.revenue)}</dd>
                </div>
                <div>
                  <dt>Total orders</dt>
                  <dd>{integer(bauCohort.orders)}</dd>
                </div>
              </dl>
            </article>
          </div>
        </section>

        <section className="section" aria-labelledby="comparison-heading">
          <div className="section-heading">
            <div>
              <p className="eyebrow">Apples-to-apples performance</p>
              <h2 id="comparison-heading">Customer quality comparison</h2>
            </div>
            <span className="matched-badge">Same acquisition period · 12-month window</span>
          </div>
          <div className="table-wrap metric-table">
            <table>
              <thead>
                <tr>
                  <th scope="col">Metric</th>
                  <th scope="col">Creator-acquired</th>
                  <th scope="col">BAU customers</th>
                  <th scope="col">Difference</th>
                </tr>
              </thead>
              <tbody>
                {metrics.map((metric) => {
                  const percentageLift = Math.round(
                    ((metric.creator - metric.bau) / metric.bau) * 100,
                  )
                  const difference =
                    metric.difference === 'points'
                      ? `+${metric.creator - metric.bau} pts`
                      : `+${percentageLift}%`

                  return (
                  <tr key={metric.label}>
                    <th scope="row">
                      <span className="metric-name">{metric.label}</span>
                      <small>{metric.description}</small>
                    </th>
                    <td className="creator-value">
                      <strong>{formatMetric(metric.creator, metric.format)}</strong>
                    </td>
                    <td><strong>{formatMetric(metric.bau, metric.format)}</strong></td>
                    <td><span className="lift-pill">{difference}</span></td>
                  </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
          <p className="table-note">
            BAU includes non-creator new customers acquired during the same
            period. Repeat-purchase AOV only includes customers who returned;
            repeat revenue per customer accounts for the full cohort.
          </p>
        </section>

        <section className="section" aria-labelledby="halo-heading">
          <div className="section-heading">
            <div>
              <p className="eyebrow">Product halo</p>
              <h2 id="halo-heading">Do creator customers explore the catalog?</h2>
            </div>
          </div>
          <div className="halo-panel">
            <div className="halo-hero">
              <span className="halo-value">{haloLift.toFixed(1)}×</span>
              <strong>more non-promoted product revenue per customer</strong>
              <p>
                Creator-acquired customers generated {currency(productHalo.creatorRevenuePerCustomer)}
                {' '}per customer outside promoted products, compared with{' '}
                {currency(productHalo.bauRevenuePerCustomer)} for BAU.
              </p>
            </div>
            <div className="halo-bars" aria-label="Non-promoted revenue comparison">
              <div className="bar-row">
                <div className="bar-label">
                  <span>Creator-acquired</span>
                  <strong>{currency(productHalo.creatorRevenuePerCustomer)}</strong>
                </div>
                <div className="bar-track">
                  <span className="bar-fill creator-fill" style={{ width: '100%' }} />
                </div>
              </div>
              <div className="bar-row">
                <div className="bar-label">
                  <span>BAU customers</span>
                  <strong>{currency(productHalo.bauRevenuePerCustomer)}</strong>
                </div>
                <div className="bar-track">
                  <span className="bar-fill bau-fill" style={{ width: `${(productHalo.bauRevenuePerCustomer / productHalo.creatorRevenuePerCustomer) * 100}%` }} />
                </div>
              </div>
            </div>
            <dl className="halo-stats">
              <div>
                <dt>Cross-category purchase rate</dt>
                <dd>{productHalo.creatorCrossCategoryRate}% <span>vs {productHalo.bauCrossCategoryRate}% BAU</span></dd>
              </div>
              <div>
                <dt>Distinct products purchased</dt>
                <dd>{productHalo.creatorProductsPurchased} <span>vs {productHalo.bauProductsPurchased} BAU</span></dd>
              </div>
            </dl>
          </div>
          <p className="table-note">
            “Non-promoted” excludes the product or category featured in the
            attributed creator campaign. This is observed behavior, not proof of causation.
          </p>
        </section>

        <footer className="cta">
          <div>
            <p className="eyebrow">Your data, your answer</p>
            <h2>Want to see what your ambassadors are actually worth?</h2>
            <p>We’ll build this comparison from your sales and attribution data.</p>
          </div>
          <a className="cta-link" href={`mailto:${CONTACT_EMAIL}?subject=InfluSight%20cohort%20analysis`}>
            Analyze my ambassador program
          </a>
        </footer>
      </div>
    </div>
  )
}

export default App
